int translate();
void program();
void pro_hdr();
void pro_body();
void DCL_LIST();
void CONST_DCL();
void CONST_STMT();
void VAR_DCL();
void VAR_STMT();
void STMT_LIST();
void STATEMENT(Token token);
void ASSIGN_STMT(Token token);
void READ_STMT(Token token);
void PRINT_STMT(Token token);
void PRINTLN_STMT(Token token);
void IF_STMT(Token token);
void WHILE_STMT(Token token);
