int translate();
void program();
void pro_hdr();
void pro_body();
void DCL_LIST();
void CONST_DCL();
void CONST_STMT();
void LITERAL(Token token);
void VAR_DCL();
void VC_ERR(char *err_message);
void VC_MATCH(TokenType token);
void VC_CHECK(TokenType op, TokenType op1, TokenType op2, TokenType op3, TokenType op4, TokenType op5, TokenType op6, TokenType op7, TokenType op8);
int is_datatype_except_const(Token token);
